#!/bin/sh

docker run --rm -it \
    -v /wow-docker/app:/appdata \
    -v /wow-docker/TrinityCore-Bot-3.3.5/entrypoint.sh:/entrypoint.sh \
    --name wow \
    -p 8085:8085 -p 3724:3724 -p 3306:3306 \
    -e EXTERNAL_ADDRESS=127.0.0.1 \
    wow:3.3.5-bot