name: Docker build push
on:
  # 手动触发事件
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Get repo and time
      id: info
      uses: actions/github-script@v3.1
      with:
        result-encoding: string
        script: |
          core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
          core.setOutput('owner', `${context.repo.owner}`);
          core.setOutput('key',  `${context.repo.owner}-${context.repo.repo}`);
          return context.repo.repo;
    - name: checkout 
      uses: actions/checkout@v2
    - name: Build Docker Image
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'docker.io'
        namespaces: ${{ steps.info.outputs.owner }}
        repository_name: ${{ steps.info.outputs.result }}
        user_name: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image_version: 'latest'
        docker_file: '.'
    - name: Get pre step result output image_pull_url
      run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"